//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Proyecto de Programacion Avanzada.rc
//
#define IDD_DIALOG1                     101
#define IDD_Incio                       103
#define IDD_Agenda                      105
#define IDD_Editdoc                     107
#define IDD_NuevaCita                   109
#define IDD_DIALOG2                     111
#define IDD_PAGO                        113
#define IDD_DIALOG3                     115
#define IDD_VENTANAFINAL                115
#define IDR_MENU1                       117
#define IDD_MOSTRARinfo                 118
#define IDD_DIALOG4                     120
#define IDD_MODIFICAR                   120
#define IDD_DIALOG5                     122
#define IDD_ELIMINARCITA                122
#define IDC_Nombre1                     1001
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_BUTTON2                     1005
#define IDC_EDIT6                       1005
#define IDC_BUTTON1                     1006
#define IDC_EDIT7                       1006
#define IDC_BUTTON3                     1007
#define IDC_EDIT8                       1007
#define IDC_BUTTON4                     1008
#define IDC_ELIMINAR                    1008
#define IDC_InfDoc                      1011
#define IDC_NuevaCita                   1012
#define IDC_Agenda                      1013
#define IDC_Salir                       1015
#define IDC_Modificar                   1017
#define IDC_ACEPTAR                     1019
#define IDC_CANCELAR                    1020
#define IDC_Cedula1                     1021
#define IDC_CITAS                       1022
#define IDC_COMBO1                      1023
#define IDC_COMBO2                      1024
#define IDC_COMBOMASCOTA                1025
#define IDC_EDIT3                       1026
#define IDC_NomMacota                   1026
#define IDC_EDIT4                       1027
#define IDC_Motivo                      1027
#define IDC_EDIT5                       1028
#define IDC_Costo                       1028
#define IDnc_Nombre                     1029
#define IDCnc_Nombre                    1029
#define IDnc_CANCEL                     1030
#define IDnc_Agendar                    1031
#define IDC_NumTel                      1032
#define IDC_DATETIMEPICKER1             1033
#define IDC_DATETIME                    1033
#define IDCpago_Aceptar                 1044
#define IDCpago_Cancelar                1045
#define IDC_LIST1                       1046
#define IDCagenda_PAGAR                 1047
#define IDpago_Confirm                  1048
#define IDpago_CANCEL                   1049
#define IDC_RADIO1                      1050
#define IDC_RADIO2                      1051
#define IDC_RADIO3                      1052
#define IDC_DATETIMEPICKER2             1053
#define ID_Sisalir                      1054
#define ID_Nosalir                      1055
#define IDCagenda_DESPLEGAR             1056
#define IDC_REGRESAR1                   1058
#define IDC_FECHA                       1059
#define IDC_HORA                        1060
#define IDC_NOMBRE                      1061
#define IDC_TELEFONO                    1062
#define IDC_ESPECIE                     1063
#define IDC_NOMBREmascota               1064
#define IDC_DATETIME2                   1065
#define IDC_DATETIMEPICKER3             1066
#define IDCnc_Nombre2                   1067
#define IDC_NumTel2                     1068
#define IDC_COMBOMASCOTA2               1069
#define IDC_NomMacota2                  1070
#define IDC_Motivo2                     1071
#define IDC_Costo2                      1072
#define IDnc_CONFIRMAR                  1073
#define IDnc_CANCEL2                    1074
#define IDCelim_ELIMINAR                1075
#define IDC_FECHA2                      1076
#define IDC_HORA2                       1077
#define IDC_NOMBRE2                     1078
#define IDC_TELEFONO2                   1079
#define IDC_ESPECIE2                    1080
#define IDC_NOMBREmascota2              1081
#define IDC_AgregarFoto                 1082
#define IDC_imagen                      1083
#define IDC_TOTAL                       1084
#define IDC_imagen3                     1084
#define IDC_3meses                      1085
#define IDC_6meses                      1086
#define IDC_12meses                     1087
#define IDC_Nombredeldoctor             1088
#define IDC_RADIO4                      1089
#define IDC_Decontado                   1090
#define IDC_imagen2                     1091
#define IDC_Nomdoc                      1092
#define IDC_DR                          1093
#define IDC_Cambiarfoto                 1096
#define IDC_foto2                       1097
#define IDC_Agregar2                    1098
#define IDC_Cambiarfoto2                1099
#define IDC_foto1                       1100
#define IDC_primerafoto                 1100
#define IDC_izq                         1101
#define IDC_der                         1102
#define IDC_LOGIN                       1103
#define IDC_doctor                      1104
#define IDC_doc2                        1105
#define IDC_AplicarFiltro               1106
#define IDC_CancelarFiltro              1107
#define BTN_INFODOC                     40001
#define BTN_NUEVACITA                   40002
#define BTN_AGENDA                      40003
#define BTN_SALIR                       40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
